### PR TITLE
WIP: Merge pulp functionality into a single role

### PR DESCRIPTION
**Pull request by Wasaac**

### CODE REVIEW

**Comment by mnasiadka** [comment]
@Wasaac I'd like to understand why do you want to merge them into one role. It doesn't really fit a purpose when someone would want to only define/update/delete distribution or define/update/delete publication.

**Comment by Wasaac** [comment]
> @Wasaac I'd like to understand why do you want to merge them into one role. It doesn't really fit a purpose when someone would want to only define/update/delete distribution or define/update/delete publication.

Sure! The workflow always requires the previous step to have been completed: 
* repository -> remote sync -> publication -> distribution. Including them in the same role allows us to enforce ordering, use task output without introducing dependencies across roles and avoids roles with a single module invokation (might as well be done in a play). 
If an operator wants to avoid syncing or publishing/distributing I've included flags to allow that.

**Review by markgoddard — CHANGES_REQUESTED** [review]
Disagree with the approach - I prefer a modular approach, since these activities may not always be coupled.

**Comment by Wasaac** [comment]
> Disagree with the approach - I prefer a modular approach, since these activities may not always be coupled.

If one needs to perform a single part of the workflow there's already squeezer modules for that - wrapping them in roles feels like unnecessary indirection when its just as easy to invoke the module. 

Considering a couple situations:
1. First run - All steps required
2. Maintenance check - Ensure repo, publication and distribution exist, don't sync
3. Fresh sync - Ensure repo exists and sync, don't publish or distribute
4. Release previously sync'd - Ensure repo exists, don't sync, publish and distribute last or pinned version.

Looking at the [recommended workflow](https://docs.pulpproject.org/pulpcore/workflows/promotion.html#distributions) for promotion I believe this approach could be easily adapted to distributing different publications across environments:
* flag to disable syncing always on in production
* publication version pinned in production config
* user config could add optional environment suffix to distribution name, allowing reuse of other components.

If your disagreement stems from the clumsiness of providing `-e "pulp_sync_remotes=false "` or `-e "pulp_distribute=false"` to disable functionality then I'd propose having separate playbooks for the different usecases. 
I could possibly be persuaded that the publication + distribution step should be moved to a separate role but I think we should test out the workflow as is first.

**Comment by mnasiadka** [comment]
I think we need to have the desired use in mind, not just the recommended workflow.

I can understand that someone would like to make his life simple and just define a repo, get it synced and published - but it's not what were after.

Having those functionalities in separate roles do not exclude your approach (reusing variables between roles in one play), having all in one role enforces running of multiple tasks that are not required in most cases.

Following your rationale:
_If one needs to perform a single part of the workflow there's already squeezer modules for that - wrapping them in roles feels like unnecessary indirection when its just as easy to invoke the module._

Let's just dump this collection and write multiple playbooks.

**Comment by Wasaac** [comment]
> I think we need to have the desired use in mind, not just the recommended workflow.
> 
> I can understand that someone would like to make his life simple and just define a repo, get it synced and published - but it's not what were after.
> 
> Having those functionalities in separate roles do not exclude your approach (reusing variables between roles in one play), having all in one role enforces running of multiple tasks that are not required in most cases.

Enforcing implies they can't be skipped - that's not the case. The alternative is either coding that skip logic in a playbook that calls multiple roles or requiring sequential playbooks to be run - this approach provides that logic to the user without complicating playbooks. Note its also sane for any given step to have run all previous steps except syncing the remote.
 
> Following your rationale:
> _If one needs to perform a single part of the workflow there's already squeezer modules for that - wrapping them in roles feels like unnecessary indirection when its just as easy to invoke the module._
> 
> Let's just dump this collection and write multiple playbooks.

Clearly playbooks aren't the best means of sharing ansible but I get your point. Ignoring the 'do we need a collection' discussion for now, I see no difference between two playbooks calling a role each and two playbooks calling the same role with different options.

If you can describe an operation/scenario/workflow that this approach can't handle I'd be happy to change my mind.

**Comment by mnasiadka** [comment]
Your approach is fine, but if we want to define a second distribution of an existing publication - it will require us to write additional playbooks/roles to do that - since you loop on results from a publication (which won't take place in that scenario).
Probably there are more scenarios that I don't have time to think of right now.

**Comment by Wasaac** [comment]
> Your approach is fine, but if we want to define a second distribution of an existing publication - it will require us to write additional playbooks/roles to do that - since you loop on results from a publication (which won't take place in that scenario).

I've added a first attempt at prefixing the distribution name with an environment which should hopefully allow multiple distributions of the same publication. Still testing.

Assuming we want to distribute a publication (rather than a repository version), the publication module should always run - it needs to check that the required version of the publication exists (latest is default when otherwise not specified). That should be idempotent regardless of whether the publication version has been pinned or left to latest.

This has the added benefit of outputting the pulp_href attribute used by the distribution module, allowing the operator to pin distributions to a publication version in config (rather than pinning by pulp_href).

**Comment by markgoddard** [comment]
The assumption of a 1 to 1 mapping between distributions and repositories doesn't seem right. There are likely to be N distributions for each repository. In our case, that might be a list of tested and proven snapshots, plus some labels for snapshots that are flowing through a release pipeline.

e.g. there is one CentOS base repository, but we want to expose different snapshots of it via distributions.

**Comment by markgoddard** [comment]
> > The assumption of a 1 to 1 mapping between distributions and repositories doesn't seem right. There are likely to be N distributions for each repository. In our case, that might be a list of tested and proven snapshots, plus some labels for snapshots that are flowing through a release pipeline.
> 
> Correct - a repository can have many distributions (and publications) but a distribution must have one repository and one publication. This establishes the dependency on earlier steps that I think is best captured in one role.
> 
> > e.g. there is one CentOS base repository, but we want to expose different snapshots of it via distributions.
> 
> The aim of the last commit was to create a new distribution for different environments with each `pulp_distribution_env` value provided by branch specific config.

So each environment would repeat the same set of repo steps, and have a unique distribution? That doesn't seem right to me.

I think we're making a lot of assumptions about how this is going to work. Will each 'environment' live in a branch? Could there instead be a list of distributions that point to RepositoryVersions?

**Comment by markgoddard** [comment]
I think we've decided against this approach.

**Pull request closed without merging**
